# Generated by Django 4.2.29 on 2026-03-20 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_resolution', models.CharField(choices=[('4k', '4K'), ('1080p', '1080p'), ('720p', '720p'), ('480p', '480p')], default='1080p', max_length=10)),
                ('frame_rate', models.IntegerField(choices=[(60, '60 fps'), (30, '30 fps'), (24, '24 fps')], default=30)),
                ('video_codec', models.CharField(choices=[('vp9', 'VP9'), ('vp8', 'VP8'), ('h264', 'H.264')], default='vp9', max_length=10)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('audio_codec', models.CharField(choices=[('opus', 'Opus'), ('aac', 'AAC')], default='opus', max_length=10)),
                ('audio_bitrate', models.IntegerField(choices=[(128, '128 kbps'), (192, '192 kbps'), (256, '256 kbps'), (320, '320 kbps')], default=192)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording Settings',
                'verbose_name_plural': 'Recording Settings',
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeybindPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stop_key', models.CharField(default='Space', max_length=50)),
                ('discard_key', models.CharField(default='Escape', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keybind_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('equal', 'Equal')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('video_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_left', to='projects.video')),
                ('video_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_right', to='projects.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
