# Generated by Django 4.2.29 on 2026-04-24 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to=settings.AUTH_USER_MODEL),
        ),
    ]
